<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
    <title>CSNHL</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!--Scales the display to the same resolution on all devices-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Import Style sheet-->
    <link rel="stylesheet" type="text/css" href="main.css">
    <!--Import Jquery for JS functions-->
</head>

<body>
   <?php include_once('header.php'); ?>
    <noscript>
        For full functionality of this site it is necessary to enable JavaScript.
        Here are the <a href="https://www.enable-javascript.com/" style='text-decoration: underline;'>
            instructions how to enable JavaScript in your web browser</a>.
    </noscript>
    <div id="root">
        <!-- LANDING VIEW -->
        <div id="home" class="section">
            <h5>CHAMPIONS</h5>
            <h5 class="previousYear"></h5>
            <h2 id="seasonWinners">ChampsName</h2>
            <img id="featureImg" />
            <!--            featureimage src is generated by a function that will determine the year and then populate the src field with the correct image-->
            <table id="awards">
                <tr id="lastSeasonAwardTitles">
                    <th id="vezinaAward" width='250'>Vezina Award</th>
                    <th id="pcAward" width='250'>Players Choice Award</th>
                    <th id="pointsAward" width='250'>Points Leader</th>
                </tr>
                <tr id="lastSeasonAwardsNames" align='center'>
                    <td id="lastSeasonVezinaWinner">Alessandro Lupo</td>
                    <td id="lastSeasonPlayerChoiceWinner">Dave Dillion</td>
                    <td id="lastSeasonPointsLeader">Jeff Scott</td>
                </tr>
                <tr class="lastSeasonAward" align='center'>
                    <td id="point1">3.10 GAA</td>
                    <td id="point2"></td>
                    <td id="point3">29G 9A 38Pts</td>
                </tr>
            </table>

        </div>
        <!-- SCHEDULE -->
        <div id="schedule" class="section">
            <h1>SCHEDULE</h1>
            <h5 class='currentSeasonYear'></h5>
            <h5>GAME SCHEDULE</h5>
            <div id='nextGame'>Banner</div>
            <a class="button" target="_blank" href="printschedule.html">Print Schedule</a>
            <table name="schedule_table" class='desktop' id="deskSchedule" title='futureGames'>
                <tr>
                    <th rowspan="2">Date</th>
                    <th colspan="3">7PM</th>
                    <th colspan="3">8PM</th>
                    <th colspan="3">9PM</th>
                </tr>
                <tr>
                    <td>7home</td>
                    <td>vs</td>
                    <td>7away</td>
                    <td>8home</td>
                    <td>vs</td>
                    <td>8away</td>
                    <td>9home</td>
                    <td>vs</td>
                    <td>9away</td>
                </tr>

            </table>
            <table id='mobileSchedule' class='mobile' title="futureGames">
                <tr>
                    <th colspan='3'>Date</th>
                </tr>
                <tr>
                    <th colspan='3'>7PM</th>
                </tr>
                <tr>
                    <td>7home</td>
                    <td>vs</td>
                    <td>7away</td>
                </tr>
                <tr>
                    <th colspan='3'>8PM</th>
                </tr>
                <tr>
                    <td>8home</td>
                    <td>vs</td>
                    <td>8away</td>
                </tr>
                <tr>
                    <th colspan='3'>9PM</th>
                </tr>
                <tr>
                    <td>9home</td>
                    <td>vs</td>
                    <td>9away</td>
                </tr>
            </table>
        </div>
        <!-- STATISTICS -->
        <div id="stats" class="section">
            <h1>STATISTICS</h1>
            <h5 class='currentSeasonYear'></h5>
            <h6>PAST GAMES</h6>
            <table name="gameStats_table" class='desktop' id="deskGamesPast" title='PastGames'>
                <tr>
                    <th>Date</th>
                    <th colspan='5'>7PM</th>
                    <th colspan='5'>8PM</th>
                    <th colspan='5'>9PM</th>
                </tr>
                <?php
                include_once('current-mysql.php');
                $sql = "SELECT * FROM PastGames";
                $result = $conn->query($sql);
                if ($result->num_rows > 0) {
                    // output data of each row
                    $i = 0;
                    while($row = $result->fetch_assoc()) {
                        $gamedate = explode(" ", $row['date']);
                        if ($i%3 == 0 && $i != 0){
                            echo "</tr>";
                        }
                        if ($i%3 == 0){
                            echo "<tr><th class='gamedate'>{$gamedate[0]}</th>";
                        }
                        echo "<td>{$row['teamA']}</td><td>{$row['goalsA']}</td><td>vs</td><td>{$row['goalsB']}</td><td>{$row['teamB']}</td>";
                        
                    $i = $i + 1;
                    }
                }
                else {
                    echo "There was a problem connecting to the server";
                }
                    ?>
            </table>
            <table class='mobile' id='mobileGamesPast' title="PastGames">
                <?php
                $sql = "SELECT * FROM PastGames";
                $result = $conn->query($sql);
                if ($result->num_rows > 0) {
                    // output data of each row
                    while($row = $result->fetch_assoc()) {
                        echo "<tr><th colspan='5'>{$row['date']}</th></tr>";
                        echo "<tr><td colspan='2'>{$row['teamA']}</td><td rowspan='2'>vs</td><td colspan='2'>{$row['teamB']}</td></tr>";
                        echo "<tr><td>Goals</td><td>{$row['goalsA']}</td><td>{$row['goalsB']}</td><td>Goals</td></tr>";
                    }
                }
                else {
                    echo "There was a problem connecting to the server";
                }
                
                ?>
            </table>
            <div id="standings">
                <h3>STANDINGS</h3>
                <table class='standings'>
                    <tr>
                        <th colspan="9">
                            <h4>REGULAR STANDINGS</h4>
                        </th>
                    </tr>
                    <tr>
                        <th>Team</th>
                        <th>GP</th>
                        <th>W</th>
                        <th>L</th>
                        <th>T</th>
                        <th>Pts</th>
                        <th>GF</th>
                        <th>GA</th>
                        <th>+/-</th>
                    </tr>
                    <?php
                    $mysql = "SELECT * FROM regularStandings ORDER BY pts desc";
                    $result = $conn->query($mysql);
                    if($result -> num_rows > 0)
                    {
                        while($row = $result->fetch_assoc())
                        {
                            echo "<tr><td class='rrteams'>{$row['team']}</td><td>{$row['gp']}</td><td>{$row['w']}</td><td>{$row['l']}</td><td>{$row['t']}</td><td>{$row['pts']}</td><td>{$row['gf']}</td><td>{$row['ga']}</td><td>{$row['diff']}</td></tr>";
                        }
                    }
                    else {
                        echo "There was a problem retrieving Regular Season Standings";
                    }
                    ?>
                </table>
                <br>
                <!--
                <table class='standings'>
                    <tr>
                        <th colspan="9">
                            <h4>ROUND ROBIN STANDINGS</h4>
                        </th>
                    </tr>
                    <tr>
                        <th>Team</th>
                        <th>GP</th>
                        <th>W</th>
                        <th>L</th>
                        <th>T</th>
                        <th>Pts</th>
                        <th>GF</th>
                        <th>GA</th>
                        <th>+/-</th>
                    </tr>
                </table>
-->

                <table id="playerStats" class="standings">
                    <tr>
                        <th colspan='6'>
                            <h4>PLAYERS STATISTICS</h4>
                        </th>
                    </tr>
                    <tr>
                        <th>Player</th>
                        <th>Team</th>
                        <th>Goals</th>
                        <th>Assists</th>
                        <th>Points</th>
                        <th>PIM</th>
                    </tr>
                    <?php
                    $mysql = "SELECT * FROM Players ORDER BY points desc";
                    $result = $conn->query($mysql);
                    if($result -> num_rows > 0)
                    {
                        while($row = $result->fetch_assoc())
                        {
                            echo "<tr><td>{$row['name']}</td><td>{$row['team']}</td><td>{$row['goals']}</td><td>{$row['assists']}</td><td>{$row['points']}</td><td>{$row['penaltyMin']}</td></tr>";
                        }
                    }
                    else {
                        echo "There was a problem retrieving Player Stats";
                    }
                    $conn->close();
                    ?>
                </table>
            </div>
        </div>
        <!-- ABOUT -->
        <div id="about" class="section">
            <h1>CREEMORE SUNDAY NIGHT HOCKEY LEAGUE</h1>
            <p>We are a 6 team league with playing times of 7pm, 8pm and 9pm on Sundays. Registration has been set at $260 per player and must be paid as follows:
                <br> By mid August - <b>$80</b>
                <br> By mid September - <b>$100</b>
                <br> By mid December - <b>$80</b>
                <br>
            </p>
            <p>
                Current player are guaranteed a spot by returning their registration form by <b>April 1st.</b>
            </p>
            <p>
                In the interest of making fair teams players must be willing to play for any team. That being said every effort will be made to have players grouped with those they wish to play with. Indicate on your registration from who you wish play with.
            </p>

            <h2>About Us</h2>
            <p>
                This was a four team league that started in October 2010.
                <br> The effort to form a league on Sunday nights in Creemore resulted from several groups of local pick up hockey players wanting to form teams and play organized games. There is a wide range of ages and skill levels. Games were three running fifteen minute periods, with games times of 8 and 9pm
            </p>

            <h2>Rules</h2>
            <h6>Arena Rules</h6>
            <p>
                <i><b>Arena rules</b></i> must be respected. We need to vacate the premises according to their wishes. Our ice times are on loan from Creemore minor hockey association who use the ice prior to ours. We need to have a good relationship with the operators of the facility and the CMHA if we wish to continue in future years.
            </p>
            <h6>Referees</h6>
            <p>
                <i><b>DO NOT MOUTH OFF TO THE REFS.</b></i> We can't operate without them so be prepared to stifle yourself and/ or your team-mates.
            </p>

            <h2>Games</h2>
            <h6>Regular Season/ Round Robin</h6>
            <p>
                Games will be three running time 15 minutes periods, played during one hour less flood and a short warm-up. If the score difference is three or less, stop time will occur during the last three minutes.</p>
            <p>Teams must have five players of more to avoid forfeit.</p>
            <p>No center ice red line, slap shots or body checking/ hitting.</p>
            <h6>Semi-final/ Final</h6>
            <p>
                Games will be three 15 minute periods of stop time. There will be a flood every 2 periods over the 2 games. If the score difference is more than 3 goals the clock will run. If the score is tied at the end of the game, a 5 minute <b>sudden death overtime</b> period will be played 5 on 5 with all other regular league rules. If the score is still tied we will play 1 minute buzzer time intervals starting with 4 on 4 and reducing a player each time. There will be no changing on the fly. If the score is still tied at the end of this 4 minute overtime we will have a shoot-out. Each team will be give three shots. After each team has taken three shots, if the score remains tied, the shoot-out will proceed to a "Sudden Death" format. No player May shoot twice until everyone who is eligible has shot.
            </p>
            <p>Players will serve 2 minutes for all minor penalties during the play-off's regardless of the infraction taking place during stop or run time.
            </p>

            <h2>Tie- Breaking Format</h2>
            <h6>Regular Season</h6>
            <p>
                When 2 or more teams are tied in the standings, to break the tie, the following criteria in the following order will be used,
            </p>
            <p>
                1 - Most Wins
                <br> 2 - Head-to-Head
                <br> 3 - Best Goal Difference (GF- GA)
                <br> 4 - Most Goals
                <br> 5 - Least Penalized
                <br>
            </p>
            <h6>Round Robin</h6>
            <p>
                When 2 or more teams are tied in the standings, to break the tie, the following criteria in the following order will be used,
            </p>
            <p>
                1 - Most Wins
                <br> 2 - Head-to-Head
                <br> 3 - Best Goal Difference (GF- GA)
                <br> 4 - Most Goals
                <br> 5 - Regular Season Standings
                <br>
            </p>


            <h2>Penalties</h2>
            <h6>Minor Penalties</h6>
            <p>
                Players will serve three minute minor penalties.
            </p>
            <p>
                Three minor penalties in one game will results in ejection from game.
            </p>
            <h6>Major Penalties</h6>
            <p>
                1st Offence = 1 game
                <br> 2nd Offence = 3 games
                <br> 3rd Offence = Balance of season or calendar year
            </p>
            <p>
                All major penalties for occurrences, such as fighting or intentional stick infractions, will be reviewed by committee to determine the length of suspensions. This committee will act in the interest of the fun and safety of the majority of players as it's highest priority. Suspensions will be increased beyond the above stated minimums at the committees discretion. No refund of registration fee should be expected by suspended players.
            </p>
        </div>
        <!-- HISTORY -->
        <div id="historyMain" class="section">
            <h1>HISTORY</h1>
            <div id="historylinks">
                <div class="pageLinks">
                    <a href="history/2017winners.html">
                        <img class='historyLinkImg' src="images/logo.png">
                        <historyYear>2017/2018</historyYear>
                        <historyTeam>Stayner</historyTeam>
                    </a>
                </div>
                <div class="pageLinks">
                    <a href="history/2016winners.html">
                        <img class='historyLinkImg' src="images/logo.png">
                        <historyYear>2016/2017</historyYear>
                        <historyTeam>Stayner</historyTeam>
                    </a>
                </div>
                <div class="pageLinks">
                    <a href="history/2015winners.html">
                        <img class='historyLinkImg' src="images/logo.png">
                        <historyYear>2015/2016</historyYear>
                        <historyTeam>New Lowell</historyTeam>
                    </a>
                </div>
                <div class="pageLinks">
                    <a href="history/2014winners.html">
                        <img class='historyLinkImg' src="images/logo.png">
                        <historyYear>2014/2015</historyYear>
                        <historyTeam>Coates Creek</historyTeam>
                    </a>
                </div>
                <div class="pageLinks">
                    <a href="history/2013winners.html">
                        <img class='historyLinkImg' src="images/logo.png">
                        <historyYear>2013/2014</historyYear>
                        <historyTeam>Belarus</historyTeam>
                    </a>
                </div>
                <div class="pageLinks">
                    <a href="history/2012winners.html" target="_page">
                        <img src="images/logo.png">
                        <historyYear>2012/2013</historyYear>
                        <historyTeam>Belarus</historyTeam>
                    </a>
                </div>
                <div class="pageLinks">
                    <a href="history/2011winners.html" target="_page">
                        <img src="images/logo.png">
                        <historyYear>2011/2012</historyYear>
                        <historyTeam>Garner</historyTeam>
                    </a>
                </div>
                <div class="pageLinks">
                    <a href="history/2010winners.html" target="_page">
                        <img src="images/logo.png">
                        <historyYear>2010/2011</historyYear>
                        <historyTeam>Cashtown Whiskey Jacks</historyTeam>
                    </a>
                </div>


            </div>
        </div>
        <!-- CONTACTS -->
        <div id="contacts" class="section">
            <h1>CONTACTS</h1>
            <div class="contact">
                <h2>President</h2>
                <address>Shawn Hughson
                    <br>705-796-7536
                    <br><a href="mailto:shawnhughson@gmail.com">shawnhughson@gmail.com</a></address>
            </div>

            <div class="contact">
                <h2>Team: Herbtown</h2>
                <address>Sean Hayward
                    <br>705-720-4252
                    <br><a href="mailto:sean07@rogers.com">sean07@rogers.com</a></address>
            </div>

            <div class="contact">
                <h2>Team: Belarus</h2>
                <address>Wade Marsh
                    <br>705-428-5575
                    <br><a href="mailto:wmarsh@belarus.ca">wmarsh@belarus.ca</a></address>
            </div>

            <div class="contact">
                <h2>Team: Stayner Wolf Pack</h2>
                <address>Mike Foster
                    <br>705-466-5244</address>
            </div>

            <div class="contact">
                <h2>Team: Cashtown Whiskey Jacks</h2>
                <address>Ed Van Severen
                    <br>705-466-3754
                    <br><a href="mailto:edvanseveren@gmail.com">edvanseveren@gmail.com</a></address>
            </div>

            <div class="contact">
                <h2>Team: New Lowell Hawks</h2>
                <address>Rich Gill
                    <br>705-424-7616
                    <br><a href="mailto:richgill@live.ca">richgill@live.ca</a></address>
            </div>

            <div class="contact">
                <h2>Team: Coates Creek</h2>
                <address>Jeremy Van Severen
                    <br>705-424-1773</address>
            </div>
        </div>
        <!-- SPONSORS -->
        <div id="sponsors" class="section">
            <h1>OUR SPONSORS</h1>
            <a href="http://www.theoldmillhousepub.com/Welcome.html" target="_page"><img class="sponsorlinks" src="images/oldmill.PNG"></a>
            <a href="http://www.belarus.ca/english/index.htm" target="_page"><img class="sponsorlinks" src="images/belarus.PNG"></a>
            <a href="http://www.coatescreekcabinetry.com/index.htm" target="_page"><img class="sponsorlinks" src="images/coatescreek.PNG"></a>
            <!--            <a href="http://www.sourceforsports.com/" target="_page"><img class="sponsorlinks" src="images/garner.PNG"></a>-->
        </div>
    </div>
    <div id="master" align="center">Designed for the Creemore Sunday Night Hockey League by Shane Guignard 2017.</div>
</body>
<script src="functions.js"></script>
<!--Import teamStats and Player databases-->
<script src='data/leagueSummary.js'></script>
<script src='data/teamStats.js'></script>

<script>
    nextGame();
    makeSchedule(a, i, g);
    schedule(g);

</script>

</html>
