<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<?php include_once('head.php') ?>
<body>
   <?php include_once('header.php'); ?>
    <noscript>
        For full functionality of this site it is necessary to enable JavaScript.
        Here are the <a href="https://www.enable-javascript.com/" style='text-decoration: underline;'>
            instructions how to enable JavaScript in your web browser</a>.
    </noscript>
    <div id="root">
        <!-- LANDING VIEW -->
        <div id="home" class="section">
            <h2>CHAMPIONS</h2>
            <h5 class="previousYear"></h5>
            <h2 id="seasonWinners">ChampsName</h2>
            <img id="featureImg" />
            <!--            featureimage src is generated by a function that will determine the year and then populate the src field with the correct image-->
            <table id="awards">
                <tr id="lastSeasonAwardTitles">
                    <th id="vezinaAward" width='250'>Vezina Award</th>
                    <th id="pcAward" width='250'>Players Choice Award</th>
                    <th id="pointsAward" width='250'>Points Leader</th>
                </tr>
                <tr id="lastSeasonAwardsNames" align='center'>
                    <td id="lastSeasonVezinaWinner">Alessandro Lupo</td>
                    <td id="lastSeasonPlayerChoiceWinner">Dave Dillion</td>
                    <td id="lastSeasonPointsLeader">Jeff Scott</td>
                </tr>
                <tr class="lastSeasonAward" align='center'>
                    <td id="point1">3.10 GAA</td>
                    <td id="point2"></td>
                    <td id="point3">29G 9A 38Pts</td>
                </tr>
            </table>

        </div>
        <!-- SPONSORS -->
        <div id="sponsors" class="section">
            <h3>OUR SPONSORS</h3>
            <a href="http://www.theoldmillhousepub.com/Welcome.html" target="_page"><img class="sponsorlinks" src="images/oldmill.PNG"></a>
            <a href="http://www.belarus.ca/english/index.htm" target="_page"><img class="sponsorlinks" src="images/belarus.PNG"></a>
            <a href="http://www.coatescreekcabinetry.com/index.htm" target="_page"><img class="sponsorlinks" src="images/coatescreek.PNG"></a>
            <!--            <a href="http://www.sourceforsports.com/" target="_page"><img class="sponsorlinks" src="images/garner.PNG"></a>-->
        </div>
    </div>
</body>
<script src="functions.js"></script>
    <script>season();</script>
</html>
